name: itcapital
services:
  app:
    build:
      context: ./docker/8.4
      args:
        WWWGROUP: 1000
    container_name: "${COMPOSE_PROJECT_NAME}-app"
    env_file:
      - .env
    networks:
      - net
      - monitoring
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      - "${APP_PORT:-8000}:80"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build:
      context: ./docker/nginx
    container_name: "${COMPOSE_PROJECT_NAME}-nginx"
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - app
    volumes:
      - ./:/var/www/html
    networks:
      - net
    restart: unless-stopped

  pgdb:
    build:
      context: ./docker/db
    container_name: "${COMPOSE_PROJECT_NAME}-pgdb"
    environment:
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_DATABASE:-appdb}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - net
    restart: unless-stopped

  redis:
    build:
      context: ./docker/redis
    container_name: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: "${COMPOSE_PROJECT_NAME}-pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - pgdb
    networks:
      - monitoring
    restart: unless-stopped

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: "${COMPOSE_PROJECT_NAME}-redisinsight"
    ports:
      - "${REDISINSIGHT_PORT:-8001}:8001"
    volumes:
      - ./docker/redisinsight:/db
    networks:
      - monitoring
    restart: unless-stopped

networks:
  net:
    driver: bridge
  monitoring:
    driver: bridge

volumes:
  db-data:
  redis-data:
