#!/usr/bin/env bash

# Change to the application directory
cd /var/www/html

# Ensure storage and cache directories exist
mkdir -p storage/logs storage/framework/{sessions,views,cache} bootstrap/cache

# Set correct ownership and permissions
chown -R sail:sail storage bootstrap/cache
chmod -R 775 storage bootstrap/cache

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
